[project]
name = "Snowflake"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Stefan G.", email = "stege00@gmail.com"},
]
dependencies = []
requires-python = ">=3.12"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true
